stages:
  - module-pipelines

backend:
  stage: module-pipelines
  trigger:
    include:
     - local: 'bb.yml'
     - template: Security/SAST.gitlab-ci.yml
     - project: 'templates/ci'
       file: 'DockerInDockerTemplate.yml'
    strategy: depend
  only:
    changes: # как только происходит изменение в папке backend, запускается дочерний пайплайн, который лежит в этой папке
     - backend/**/* 

frontend:
  stage: module-pipelines
  trigger:
    include:
     - local: 'fb.yml' 
     - template: Security/SAST.gitlab-ci.yml
     - project: 'templates/ci'
       file: 'DockerInDockerTemplate.yml'
    strategy: depend # depend нужен, если какой-нибудь дочерний пайплайн свалился, мы знали, что общий пайплайн тоже идёт с ошибкой
  only:
    changes:
     - frontend/**/*

upload-chart:
  stage: module-pipelines
  trigger:
    include:
     - local: 'upload-chart.yml' 
     - project: 'templates/ci'
       file: 'DockerInDockerTemplate.yml'
    strategy: depend # depend нужен, если какой-нибудь дочерний пайплайн свалился, мы знали, что общий пайплайн тоже идёт с ошибкой
#  only:
#    changes:
#     - upload/**/*     
