variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
    
stages:
  - test 
  - build-image-for-release
  - update-version-chart
#  - deploy
#  - ver_f_downstream
#  - deploy
#  - notify  

sonarqube-backend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd backend
    - >
      sonar-scanner
      -Dsonar.sources=.
      -Dsonar.projectKey=${SONAR_PROJECT_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN}
      -Dsonar.projectName="11_vsurin_momob"   

spotbugs-sast:
  stage: test
  script:
    - cd backend

go-test:
  stage: test
  image: golang:latest
  script:
    - cd backend
    - go test -v ./...
  allow_failure: true

build-backend-docker-image:
  stage: build-image-for-release
  image: alpine:latest
  before_script:
    - apk add docker docker-compose curl
    - until docker info; do sleep 1; done
    # переменные CI_REGISTRY_USER, CI_REGISTRY_PASSWORD, CI_REGISTRY генерятся Гитлабом, их задавать не надо
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose build backend
    - docker-compose push backend

update-version-chart:
  stage: update-version-chart
  image: gitlab.praktikum-services.ru:5050/v.surin/momostore/helm-kubectl
  script:
    #Настраиваем CLI YC и kubeconfig (неинтерактивный режим)
    - /bin/bash -s < ./helmchart_ver2.sh

    #Деплоим новую версию приложения
#    - helm upgrade momo-store ./momo-store-chart
    #Упаковываем helm-chart приложения
#    - helm package ./momo-store-chart
    #Отправляем helm-chart в Nexus
#    - curl -u ${NEXUS_REPO_LOGIN}:${NEXUS_REPO_PASSWORD} ${NEXUS_REPO_URL_HELM} --upload-file momo-store-${VERSION_UPSTREAM}.tgz 





##backend_argo_deploy:
##  stage: deploy

#for_helmchart_version_update:  
#  variables:
#    VERSION_UPSTREAM: 1.0.${CI_PIPELINE_ID}
#    ID: backend
#  stage: ver_f_downstream  
#  trigger:
#    project: v.surin/imomostore
#    branch: i01


##copy-compose-files:
##  image: alpine:latest
##  stage: deploy

##deploy-backend:
##  stage: deploy

##slack-notification-backend:
##  stage: notify
