variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
    
stages:
  - test 
#  - build-image-for-release
#  - deploy
#  - ver_f_downstream
#  - deploy
#  - notify  

sonarqube-backend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd backend
    - >
      sonar-scanner
      -Dsonar.sources=.
      -Dsonar.projectKey=${SONAR_PROJECT_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN}
      -Dsonar.projectName="11_vsurin_momob"   

spotbugs-sast:
  stage: test
  script:
    - cd backend

go-test:
  stage: test
  image: golang:latest
  script:
    - cd backend
    - go test -v ./...
  allow_failure: true

##build-backend-docker-image:
##  stage: build-image-for-release
#  image: docker:20.10.12-dind-rootless  

##backend_argo_deploy:
##  stage: deploy

##for_helmchart_version_update:  
##  stage: ver_f_downstream

##copy-compose-files:
##  image: alpine:latest
##  stage: deploy

##deploy-backend:
##  stage: deploy

##slack-notification-backend:
##  stage: notify
