variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
#  - build-for-test
  - test 
##  - build-image-for-release
##  - deploy
##  - ver_f_downstream
##  - notify 

sonarqube-frontend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - >
      sonar-scanner
      -Dsonar.sources=. 
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=${SONAR_PROJECT_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN}
      -Dsonar.projectName="11_vsurin_momof"     

spotbugs-sast:
  stage: test
  script:
    - cd frontend

##build-frontend-docker-image:
##  stage: build-image-for-release

##frontend_argo_deploy:
##  stage: deploy

##for_helmchart_version_update:  
##  stage: ver_f_downstream  

##copy-compose-files:
##  image: alpine:latest
##  stage: deploy

##deploy-frontend:
##  stage: deploy
      
##slack-notification-frontend:
##  stage: notify
