apiVersion: v2
appVersion: 1.0.572489
dependencies:
- name: backend
  repository: ""
  version: 1.0.571411
- name: frontend
  repository: ""
  version: 1.0.570361
description: momo-store Helm Chart
name: momo-store
type: application
version: 1.0.572489
