---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.ports.containerPort }}
  selector:
    app: backend
